/* ============================================================
   i18n.js: Ngôn ngữ giao diện (7 ngôn ngữ) + chuỗi UI
   Ngôn ngữ được người dùng chọn thủ công qua lá cờ, lưu trong
   chrome.storage.local, không phụ thuộc locale trình duyệt.
   ============================================================ */

const LANGUAGES = [
  { code: "en", flag: "🇺🇸", name: "English", dir: "ltr" },
  { code: "vi", flag: "🇻🇳", name: "Tiếng Việt", dir: "ltr" },
  { code: "ar", flag: "🇸🇦", name: "العربية", dir: "rtl" },
  { code: "zh", flag: "🇨🇳", name: "中文", dir: "ltr" },
  { code: "fr", flag: "🇫🇷", name: "Français", dir: "ltr" },
  { code: "ru", flag: "🇷🇺", name: "Русский", dir: "ltr" },
  { code: "es", flag: "🇪🇸", name: "Español", dir: "ltr" },
];

const DEFAULT_LANG = "en";

// t(key) sẽ tra theo ngôn ngữ hiện tại, fallback về "en" nếu thiếu
const UI_STRINGS = {
  appTitle:        { en: "AI Signboard Prompt", vi: "AI Signboard Prompt", ar: "مولّد أوصاف اللافتات", zh: "AI招牌提示词生成器", fr: "Générateur de prompts", ru: "Генератор AI-промптов", es: "Generador de prompts" },
  appSubtitle:      { en: "by Quốc Đăng Signage, Hanoi", vi: "bởi Quảng Cáo Quốc Đăng", ar: "من Quốc Đăng Signage", zh: "由 Quốc Đăng 广告制作", fr: "par Quốc Đăng Signage", ru: "от Quốc Đăng Signage", es: "por Quốc Đăng Signage" },
  brandNameLabel:   { en: "Brand name on the sign", vi: "Tên thương hiệu trên biển", ar: "اسم العلامة التجارية على اللافتة", zh: "招牌上的品牌名称", fr: "Nom de l'enseigne", ru: "Название бренда на вывеске", es: "Nombre de la marca en el letrero" },
  brandNamePlaceholder: { en: "e.g. Sunrise Coffee", vi: "Ví dụ: Cafe Bình Minh", ar: "مثال: مقهى الفجر", zh: "例如：晨光咖啡", fr: "ex. Café Aurore", ru: "напр. Кафе Рассвет", es: "ej. Café Amanecer" },
  businessTypeLabel: { en: "Business type", vi: "Loại hình kinh doanh", ar: "نوع النشاط التجاري", zh: "行业类型", fr: "Type de commerce", ru: "Тип бизнеса", es: "Tipo de negocio" },
  signTypeLabel:    { en: "Sign type", vi: "Loại biển", ar: "نوع اللافتة", zh: "招牌类型", fr: "Type d'enseigne", ru: "Тип вывески", es: "Tipo de letrero" },
  styleLabel:       { en: "Style", vi: "Phong cách", ar: "الأسلوب", zh: "风格", fr: "Style", ru: "Стиль", es: "Estilo" },
  colorToneLabel:   { en: "Color tone", vi: "Tông màu", ar: "درجة اللون", zh: "色调", fr: "Tonalité de couleur", ru: "Цветовая гамма", es: "Tono de color" },
  timeOfDayLabel:   { en: "Time of day", vi: "Thời điểm", ar: "الوقت من اليوم", zh: "时间", fr: "Moment de la journée", ru: "Время суток", es: "Momento del día" },
  angleLabel:       { en: "Camera angle", vi: "Góc nhìn", ar: "زاوية الكاميرا", zh: "拍摄角度", fr: "Angle de vue", ru: "Ракурс", es: "Ángulo de cámara" },
  frontageWidthLabel: { en: "Storefront width in meters (optional)", vi: "Mặt tiền (mét, không bắt buộc)", ar: "عرض الواجهة بالأمتار (اختياري)", zh: "店面宽度（米，选填）", fr: "Largeur de la façade en mètres (facultatif)", ru: "Ширина фасада в метрах (необязательно)", es: "Ancho de la fachada en metros (opcional)" },
  platformLabel:    { en: "AI platform", vi: "Nền tảng AI", ar: "منصة الذكاء الاصطناعي", zh: "AI 平台", fr: "Plateforme IA", ru: "AI-платформа", es: "Plataforma de IA" },
  promptPanelTitle: { en: "PROMPT", vi: "PROMPT", ar: "الوصف", zh: "提示词", fr: "PROMPT", ru: "ПРОМПТ", es: "PROMPT" },
  copyPrompt:       { en: "Copy Prompt", vi: "Copy Prompt", ar: "نسخ الوصف", zh: "复制提示词", fr: "Copier le prompt", ru: "Копировать промпт", es: "Copiar prompt" },
  copied:           { en: "Copied!", vi: "Đã copy!", ar: "تم النسخ!", zh: "已复制！", fr: "Copié !", ru: "Скопировано!", es: "¡Copiado!" },
  copyFailed:       { en: "Couldn't copy, try again", vi: "Không copy được, hãy thử lại", ar: "تعذر النسخ، حاول مرة أخرى", zh: "复制失败，请重试", fr: "Échec de la copie, réessayez", ru: "Не удалось скопировать, попробуйте снова", es: "No se pudo copiar, inténtalo de nuevo" },
  negativePromptSummary: { en: "Suggested negative prompt", vi: "Negative prompt gợi ý", ar: "الوصف السلبي المقترح", zh: "建议的负面提示词", fr: "Prompt négatif suggéré", ru: "Рекомендуемый негативный промпт", es: "Prompt negativo sugerido" },
  copyNegative:     { en: "Copy Negative Prompt", vi: "Copy Negative Prompt", ar: "نسخ الوصف السلبي", zh: "复制负面提示词", fr: "Copier le prompt négatif", ru: "Копировать негативный промпт", es: "Copiar prompt negativo" },
  saveFavorite:     { en: "☆ Save to favorites", vi: "☆ Lưu vào mẫu yêu thích", ar: "☆ حفظ في المفضلة", zh: "☆ 保存到收藏", fr: "☆ Enregistrer en favori", ru: "☆ Сохранить в избранное", es: "☆ Guardar en favoritos" },
  favoritesSummary: { en: "Saved favorites", vi: "Mẫu yêu thích đã lưu", ar: "المفضلة المحفوظة", zh: "已保存的收藏", fr: "Favoris enregistrés", ru: "Сохранённое избранное", es: "Favoritos guardados" },
  emptyHistory:     { en: "No favorites saved yet", vi: "Chưa có mẫu nào được lưu", ar: "لا توجد مفضلة بعد", zh: "还没有保存的收藏", fr: "Aucun favori enregistré", ru: "Пока нет сохранённого избранного", es: "Aún no hay favoritos guardados" },
  ctaText:          { en: "Like this concept? Get a real quote (Hanoi, Vietnam workshop).", vi: "Ưng ý với mẫu này? Nhận báo giá thi công thật tại Hà Nội.", ar: "أعجبتك هذه الفكرة؟ احصل على عرض سعر حقيقي (ورشة هانوي، فيتنام).", zh: "喜欢这个方案？获取真实报价（河内工厂制作）。", fr: "Ce concept vous plaît ? Obtenez un devis réel (atelier à Hanoï, Vietnam).", ru: "Нравится концепция? Получите реальную смету (мастерская в Ханое, Вьетнам).", es: "¿Te gusta este concepto? Solicita una cotización real (taller en Hanói, Vietnam)." },
  ctaZalo:          { en: "Chat on Zalo", vi: "Chat Zalo báo giá", ar: "الدردشة عبر Zalo", zh: "Zalo 在线咨询", fr: "Discuter sur Zalo", ru: "Написать в Zalo", es: "Chatear por Zalo" },
  ctaZaloSending:   { en: "Message copied, opening Zalo…", vi: "Đã copy tin nhắn, mở Zalo…", ar: "تم نسخ الرسالة، جارٍ فتح Zalo…", zh: "消息已复制，正在打开 Zalo…", fr: "Message copié, ouverture de Zalo…", ru: "Сообщение скопировано, открываю Zalo…", es: "Mensaje copiado, abriendo Zalo…" },
  ctaContact:       { en: "Contact page", vi: "Trang liên hệ", ar: "صفحة التواصل", zh: "联系页面", fr: "Page de contact", ru: "Страница контактов", es: "Página de contacto" },
  ctaMessage:       {
    en: (s) => `Hi Quốc Đăng, I designed a sign concept with AI: sign type "${s.sign}", style "${s.style}", color tone "${s.color}"${s.width ? `, storefront width about ${s.width}m` : ""}${s.brand ? `, brand name "${s.brand}"` : ""}. I'd like a quote to have it made.`,
    vi: (s) => `Chào Quốc Đăng, mình vừa lên ý tưởng biển bằng AI: loại biển "${s.sign}", phong cách "${s.style}", tông màu "${s.color}"${s.width ? `, mặt tiền khoảng ${s.width}m` : ""}${s.brand ? `, tên thương hiệu "${s.brand}"` : ""}. Mình muốn nhận báo giá thi công.`,
    ar: (s) => `مرحبًا Quốc Đăng، صممت فكرة لافتة بالذكاء الاصطناعي: نوع اللافتة "${s.sign}"، الأسلوب "${s.style}"، درجة اللون "${s.color}"${s.width ? `، عرض الواجهة حوالي ${s.width} متر` : ""}${s.brand ? `، اسم العلامة التجارية "${s.brand}"` : ""}. أرغب في الحصول على عرض سعر للتنفيذ.`,
    zh: (s) => `你好 Quốc Đăng，我用 AI 设计了一个招牌方案：招牌类型「${s.sign}」，风格「${s.style}」，色调「${s.color}」${s.width ? `，店面宽度约${s.width}米` : ""}${s.brand ? `，品牌名称「${s.brand}」` : ""}。想咨询制作报价。`,
    fr: (s) => `Bonjour Quốc Đăng, j'ai conçu une enseigne avec l'IA : type d'enseigne « ${s.sign} », style « ${s.style} », tonalité « ${s.color} »${s.width ? `, façade d'environ ${s.width}m` : ""}${s.brand ? `, nom de marque « ${s.brand} »` : ""}. Je souhaite un devis pour la fabrication.`,
    ru: (s) => `Здравствуйте, Quốc Đăng! Я создал(а) концепцию вывески с помощью AI: тип вывески «${s.sign}», стиль «${s.style}», цветовая гамма «${s.color}»${s.width ? `, ширина фасада около ${s.width} м` : ""}${s.brand ? `, название бренда «${s.brand}»` : ""}. Хотел(а) бы получить смету на изготовление.`,
    es: (s) => `Hola Quốc Đăng, diseñé un concepto de letrero con IA: tipo de letrero "${s.sign}", estilo "${s.style}", tono de color "${s.color}"${s.width ? `, fachada de unos ${s.width}m` : ""}${s.brand ? `, nombre de marca "${s.brand}"` : ""}. Me gustaría una cotización de fabricación.`,
  },
  footerHotline:    { en: "Hotline/Zalo", vi: "Hotline/Zalo", ar: "الخط الساخن/Zalo", zh: "热线/Zalo", fr: "Ligne directe/Zalo", ru: "Горячая линия/Zalo", es: "Línea directa/Zalo" },
  themeToggleToDark: { en: "Switch to dark mode", vi: "Chuyển chế độ tối", ar: "التبديل إلى الوضع الداكن", zh: "切换到深色模式", fr: "Passer en mode sombre", ru: "Включить тёмный режим", es: "Cambiar a modo oscuro" },
  themeToggleToLight: { en: "Switch to light mode", vi: "Chuyển chế độ sáng", ar: "التبديل إلى الوضع الفاتح", zh: "切换到浅色模式", fr: "Passer en mode clair", ru: "Включить светлый режим", es: "Cambiar a modo claro" },
  maximize: { en: "Maximize", vi: "Phóng to toàn màn hình", ar: "تكبير", zh: "最大化", fr: "Agrandir", ru: "Развернуть", es: "Maximizar" },
  restoreDown: { en: "Restore Down", vi: "Khôi phục kích thước", ar: "استعادة الحجم", zh: "还原", fr: "Restaurer", ru: "Восстановить", es: "Restaurar" },
  languageLabel:    { en: "Language", vi: "Ngôn ngữ", ar: "اللغة", zh: "语言", fr: "Langue", ru: "Язык", es: "Idioma" },
  customOption:     { en: "✏️ Custom (type your own)", vi: "✏️ Nhập tùy chỉnh", ar: "✏️ إدخال مخصص", zh: "✏️ 自定义输入", fr: "✏️ Personnalisé (saisie libre)", ru: "✏️ Свой вариант (ввести вручную)", es: "✏️ Personalizado (escribe el tuyo)" },
  customPlaceholder: { en: "Type your own…", vi: "Nhập nội dung của bạn…", ar: "اكتب ما تريده…", zh: "请输入您的内容…", fr: "Saisissez votre texte…", ru: "Введите свой вариант…", es: "Escribe lo que quieras…" },
  promptNeedsCustomInput: { en: "Please fill in the custom field(s) above to generate the prompt.", vi: "Vui lòng nhập nội dung tùy chỉnh ở trên để tạo prompt.", ar: "يرجى تعبئة الحقل المخصص أعلاه لإنشاء الوصف.", zh: "请先填写上方的自定义内容以生成提示词。", fr: "Veuillez remplir le(s) champ(s) personnalisé(s) ci-dessus pour générer le prompt.", ru: "Заполните поле(я) для своего варианта выше, чтобы создать промпт.", es: "Completa el/los campo(s) personalizado(s) arriba para generar el prompt." },
  closeButtonLabel: { en: "Close", vi: "Đóng", ar: "إغلاق", zh: "关闭", fr: "Fermer", ru: "Закрыть", es: "Cerrar" },
  storefrontPhotoLabel: { en: "Storefront photo (optional)", vi: "Ảnh mặt tiền cửa hàng (không bắt buộc)", ar: "صورة الواجهة (اختياري)", zh: "店面照片（选填）", fr: "Photo de la façade (facultatif)", ru: "Фото фасада (необязательно)", es: "Foto de la fachada (opcional)" },
  photoPlaceholder: { en: "Click or drag a photo of your storefront here", vi: "Nhấn hoặc kéo thả ảnh mặt tiền vào đây", ar: "انقر أو اسحب صورة الواجهة إلى هنا", zh: "点击或拖拽店面照片到此处", fr: "Cliquez ou déposez une photo de la façade ici", ru: "Нажмите или перетащите сюда фото фасада", es: "Haz clic o arrastra aquí una foto de la fachada" },
  photoChoose: { en: "Choose photo", vi: "Chọn ảnh", ar: "اختر صورة", zh: "选择照片", fr: "Choisir une photo", ru: "Выбрать фото", es: "Elegir foto" },
  photoChange: { en: "Change photo", vi: "Đổi ảnh khác", ar: "تغيير الصورة", zh: "更换照片", fr: "Changer de photo", ru: "Изменить фото", es: "Cambiar foto" },
  photoCopy: { en: "Copy photo", vi: "Copy ảnh", ar: "نسخ الصورة", zh: "复制照片", fr: "Copier la photo", ru: "Копировать фото", es: "Copiar foto" },
  photoCopied: { en: "Photo copied!", vi: "Đã copy ảnh!", ar: "تم نسخ الصورة!", zh: "照片已复制！", fr: "Photo copiée !", ru: "Фото скопировано!", es: "¡Foto copiada!" },
  photoCopyFailed: { en: "Couldn't copy photo", vi: "Không copy được ảnh", ar: "تعذر نسخ الصورة", zh: "无法复制照片", fr: "Impossible de copier la photo", ru: "Не удалось скопировать фото", es: "No se pudo copiar la foto" },
  photoRemove: { en: "Remove", vi: "Xoá ảnh", ar: "إزالة", zh: "移除", fr: "Supprimer", ru: "Удалить", es: "Quitar" },
  photoHintDefault: { en: "Optional. The photo stays only in your browser. When added, the prompt below is optimized to preview the sign on your real storefront.", vi: "Không bắt buộc. Ảnh chỉ được lưu trong trình duyệt của bạn. Khi thêm ảnh, prompt bên dưới sẽ được tối ưu để xem trước biển trên ảnh thật của cửa hàng.", ar: "اختياري. تبقى الصورة محفوظة في متصفحك فقط. عند إضافتها، يتم تحسين الوصف أدناه لمعاينة اللافتة على صورة واجهتك الفعلية.", zh: "选填。照片仅保存在您的浏览器中。添加照片后，下方的提示词会自动优化，用于在您真实的店面照片上预览招牌效果。", fr: "Facultatif. La photo reste uniquement dans votre navigateur. Une fois ajoutée, le prompt ci-dessous est optimisé pour prévisualiser l'enseigne sur votre vraie façade.", ru: "Необязательно. Фото хранится только в вашем браузере. После добавления промпт ниже будет оптимизирован для предпросмотра вывески на реальном фото вашего фасада.", es: "Opcional. La foto se guarda solo en tu navegador. Al añadirla, el prompt de abajo se optimiza para previsualizar el letrero sobre la foto real de tu fachada." },
  photoModeBadge: { en: "Photo mode", vi: "Chế độ ảnh thật", ar: "وضع الصورة", zh: "照片模式", fr: "Mode photo", ru: "Режим фото", es: "Modo foto" },
  photoErrorType: { en: "Please upload an image file (PNG, JPG, or WEBP).", vi: "Vui lòng chọn tệp ảnh (PNG, JPG hoặc WEBP).", ar: "يرجى تحميل ملف صورة (PNG أو JPG أو WEBP).", zh: "请上传图片文件（PNG、JPG 或 WEBP）。", fr: "Veuillez importer un fichier image (PNG, JPG ou WEBP).", ru: "Загрузите файл изображения (PNG, JPG или WEBP).", es: "Sube un archivo de imagen (PNG, JPG o WEBP)." },
  photoErrorSize: { en: "This photo is too large. Please choose one under 15MB.", vi: "Ảnh quá lớn. Vui lòng chọn ảnh dưới 15MB.", ar: "هذه الصورة كبيرة جدًا. يرجى اختيار صورة أقل من 15 ميجابايت.", zh: "该照片过大，请选择小于 15MB 的照片。", fr: "Cette photo est trop volumineuse. Choisissez-en une de moins de 15 Mo.", ru: "Это фото слишком большое. Выберите файл менее 15 МБ.", es: "Esta foto es demasiado grande. Elige una de menos de 15 MB." },
  photoErrorRead: { en: "Couldn't read this photo. Please try another one.", vi: "Không đọc được ảnh này. Vui lòng thử ảnh khác.", ar: "تعذر قراءة هذه الصورة. يرجى تجربة صورة أخرى.", zh: "无法读取该照片，请尝试其他照片。", fr: "Impossible de lire cette photo. Essayez-en une autre.", ru: "Не удалось прочитать это фото. Попробуйте другое.", es: "No se pudo leer esta foto. Prueba con otra." },
  photoErrorStorage: { en: "Couldn't save the photo (storage full). Try a smaller photo.", vi: "Không lưu được ảnh (bộ nhớ đầy). Vui lòng thử ảnh nhỏ hơn.", ar: "تعذر حفظ الصورة (التخزين ممتلئ). جرّب صورة أصغر.", zh: "无法保存照片（存储空间已满）。请尝试更小的照片。", fr: "Impossible d'enregistrer la photo (stockage plein). Essayez une photo plus petite.", ru: "Не удалось сохранить фото (нет места). Попробуйте фото меньшего размера.", es: "No se pudo guardar la foto (almacenamiento lleno). Prueba con una foto más pequeña." },
  angleDisabledHint: { en: "Not used in photo mode. It's set automatically based on your uploaded photo.", vi: "Không dùng khi có ảnh thật. Góc chụp sẽ được lấy tự động theo ảnh bạn đã tải lên.", ar: "غير مستخدم في وضع الصورة. يتم تحديده تلقائيًا حسب الصورة التي رفعتها.", zh: "照片模式下不会用到此项，将根据您上传的照片自动决定。", fr: "Non utilisé en mode photo. Il est déterminé automatiquement par votre photo importée.", ru: "Не используется в режиме фото. Определяется автоматически по вашему загруженному фото.", es: "No se usa en modo foto. Se determina automáticamente según tu foto subida." },
  copyPromptPhoto: { en: "Copy Prompt + Photo", vi: "Copy Prompt + Ảnh", ar: "نسخ الوصف + الصورة", zh: "复制提示词 + 照片", fr: "Copier le prompt + la photo", ru: "Копировать промпт + фото", es: "Copiar prompt + foto" },
  copiedWithPhoto: { en: "Copied prompt + photo!", vi: "Đã copy prompt + ảnh!", ar: "تم نسخ الوصف والصورة!", zh: "已复制提示词和照片！", fr: "Prompt + photo copiés !", ru: "Скопированы промпт и фото!", es: "¡Prompt + foto copiados!" },
  photoCopyBundleFailed: { en: "Couldn't attach the photo automatically, so only the text was copied. Click \"Copy Photo\" to copy the image separately, then paste both.", vi: "Không tự động đính kèm được ảnh nên chỉ copy được phần chữ. Hãy bấm \"Copy Photo\" để copy ảnh riêng, sau đó dán cả hai.", ar: "تعذر إرفاق الصورة تلقائيًا، لذلك تم نسخ النص فقط. انقر على \"نسخ الصورة\" لنسخ الصورة بشكل منفصل، ثم الصق كليهما.", zh: "无法自动附加照片，因此仅复制了文字。请点击“复制照片”单独复制图片，然后将两者分别粘贴。", fr: "Impossible de joindre automatiquement la photo, donc seul le texte a été copié. Cliquez sur « Copier la photo » pour copier l'image séparément, puis collez les deux.", ru: "Не удалось автоматически прикрепить фото, поэтому скопирован только текст. Нажмите «Копировать фото», чтобы скопировать изображение отдельно, затем вставьте оба.", es: "No se pudo adjuntar la foto automáticamente, así que solo se copió el texto. Haz clic en \"Copiar foto\" para copiar la imagen por separado y luego pega ambos." },
  photoCopyNote: { en: "Photo mode is on. Make sure both the photo and the prompt reach the AI: paste once with \"Copy Prompt + Photo\". If a platform only keeps the photo or the text, click \"Copy Photo\" and \"Copy Prompt\" to add the missing part in the same chat box.", vi: "Đang bật chế độ ảnh thật. Hãy đảm bảo cả ảnh và prompt đều được đưa vào AI: dán 1 lần bằng nút \"Copy Prompt + Photo\". Nếu nền tảng chỉ nhận được ảnh hoặc chữ, hãy bấm \"Copy Photo\" và \"Copy Prompt\" để dán bổ sung phần còn thiếu vào cùng ô chat.", ar: "وضع الصورة مُفعّل. تأكد من وصول كل من الصورة والوصف إلى الذكاء الاصطناعي: الصق مرة واحدة باستخدام \"نسخ الوصف + الصورة\". إذا احتفظت المنصة بالصورة أو النص فقط، انقر على \"نسخ الصورة\" و\"نسخ الوصف\" لإضافة الجزء الناقص في نفس مربع المحادثة.", zh: "照片模式已开启。请确保照片和提示词都传给 AI：先用“复制提示词 + 照片”粘贴一次。如果该平台只保留了照片或文字，请再点击“复制照片”和“复制提示词”，把缺少的部分粘贴到同一个聊天框中。", fr: "Le mode photo est activé. Assurez-vous que la photo et le prompt parviennent tous deux à l'IA : collez une fois avec « Copier le prompt + la photo ». Si la plateforme ne conserve que la photo ou le texte, cliquez sur « Copier la photo » et « Copier le prompt » pour ajouter la partie manquante dans la même zone de discussion.", ru: "Режим фото включён. Убедитесь, что и фото, и промпт попадают в AI: вставьте один раз кнопкой «Копировать промпт + фото». Если платформа сохраняет только фото или только текст, нажмите «Копировать фото» и «Копировать промпт», чтобы добавить недостающую часть в то же поле чата.", es: "Modo foto activado. Asegúrate de que tanto la foto como el prompt lleguen a la IA: pega una vez con \"Copiar prompt + foto\". Si la plataforma solo conserva la foto o el texto, haz clic en \"Copiar foto\" y \"Copiar prompt\" para añadir la parte que falta en el mismo cuadro de chat." },
};

function t(key, lang) {
  const entry = UI_STRINGS[key];
  if (!entry) return key;
  return entry[lang] ?? entry[DEFAULT_LANG] ?? key;
}
